version: '3'

services:

  task-planner-express:
    build: ./express-task-planner
    container_name: task_planner_express
    ports:
      - 3001:3000
    networks:
      - default

  task-planner-react:
    build: ./react-task-planner
    container_name: task_planner_react
    ports:
      - 3000:3000
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"
